webapp/package.json, webapp/src/app/[lang]/page.tsx, webapp/src/app/api/translations/[lang]/[msgId]/route.ts, webapp/src/components/MessageForm.tsx, webapp/yarn.lock
This PR implements saving directly to YAML. There are some issues with this, specifically the risk for race conditions. Ideally, there should be an intermediate step to save in memory before saving to YAML (which should happen periodically or when an admin triggers it).
But this is a nice proof of concept and early implementation for this functionality, which is a major improvement compared to how translate.zetkin.org works.
=> Saving to yaml

webapp/CHANGELOG.md, webapp/package.json, webapp/src/app/api/messages/route.ts, webapp/src/app/api/pull-request/route.ts, webapp/src/utils/log.ts
Remove error logging
related to issue: #32
=> 231221 remove error logging

webapp/src/utils/adapters/YamlTranslationAdapter.spec.ts
In https://github.com/zetkin/lyra/pull/49 we were seeing some seemingly random ENOENT. I am guessing these were caused by the missing mock.restore in this spec. Note that all out other usages of mock-fs restore like this.
I considered adding the afterEach at the root-describe instead to reduce risk of missing the restore if later use is added outside the inner describe. In the end, I opted for keeping it closer to the usage. I am not sure how safe it is to restore when you have not set up any mock.
=> Restore fs after each in YamlTranslationAdapter

webapp/README.md, webapp/src/Cache.ts, webapp/src/RepoGit.ts, webapp/src/app/api/pull-request/[projectName]/route.ts, webapp/src/errors.ts, webapp/src/utils/lyraConfig.spec.ts, webapp/src/utils/lyraConfig.ts, webapp/src/utils/serverConfig.spec.ts, webapp/src/utils/serverConfig.ts
Having baseBranch config in LyraConfig is not correct, because:
1. Lets say the setting baseBranch is changed from `main` to `prod` the local copy of Lyra has value of `main` and accordingly will always pull from that branch while the new baseBranch in prod containt different value
2. If we are cloning the repo from remote for the first time (we never test this yet) Lyra will throw Exception since it need to read LyraConfig to have the value of baseBranch that is needed to checkout but at the same time there is no local copy to read from
Solution: move this settings to ServerConfig
=> Move baseBranch config from lyraConfig to ServerConfig

webapp/README.md, webapp/src/Cache.ts, webapp/src/RepoGit.ts, webapp/src/app/api/messages/[projectName]/route.ts, webapp/src/app/api/pull-request/[projectName]/route.ts, webapp/src/app/api/translations/[projectName]/[lang]/[msgId]/route.ts, webapp/src/utils/adapters/MessageAdapterFactory.ts
Move all initializing git pull into RepoGit and make RepoGit shared for each unique local git clone.
As the repository specific configuration file is potentially stale, we need to do this initializing pull before any read of that configuration file. To ensure that, I replace all direct reads with a read through RepoGit. Since the factory always pulls, we know the config will be fresh after a Lyra server start.
Note that the route for creating pull-requests can now theoretically pull twice, if RepoGit was not initialzied first. That is however extremely unlikely as button the create pull requests is on a page that uses RepoGit to load its data. Anyway, I beleive we will resolve this when we implement resyncing from the remotes.
=> Make sure we have pulled before reading LyraConfig

webapp/src/app/projects/[projectName]/[lang]/page.tsx
=> Show error message in UI if file path in projects.yaml is wrong

webapp/src/app/page.tsx, webapp/src/components/HomeDashboard.tsx, webapp/src/components/ProjectCard.tsx
Replaces https://github.com/zetkin/lyra/pull/86. Fixes https://github.com/zetkin/lyra/issues/74. Addresses some of https://github.com/zetkin/lyra/issues/71 too.
It proved problematic to introduce Storybook. I don't want to get bogged down in that kind of stuff. Want my impact on Lyra to be acceleration. So here's a new pull request that simply solves the core problem in the smallest possible diff.
=> Home page (minus Storybook)

webapp/src/app/projects/[projectName]/page.tsx, webapp/src/components/CardGrid.tsx, webapp/src/components/HomeDashboard.tsx, webapp/src/components/LanguageCard.tsx, webapp/src/components/ProjectDashboard.tsx
Fixes https://github.com/zetkin/lyra/issues/75 and https://github.com/zetkin/lyra/issues/76.
Created a little `<CardGrid />` component here so that the layout code can be shared by the home page and the project page. Nice for the two of them to feel consistent with each other.
| 1 language | 2 languages | 3 languages | 4 languages |
|-|-|-|-|
| ![Screenshot 2024-05-27 at 21 35 15](https://github.com/zetkin/lyra/assets/566159/e776c426-e465-4ddb-9ed8-18d7c13c0ce0) | ![Screenshot 2024-05-27 at 21 35 01](https://github.com/zetkin/lyra/assets/566159/86472587-4828-4b20-be83-56842c320f70) | ![Screenshot 2024-05-27 at 21 34 51](https://github.com/zetkin/lyra/assets/566159/c926fd01-ea10-48b5-b77d-3cc459bbf5b4) | ![Screenshot 2024-05-27 at 21 34 …
=> Create project page

webapp/src/app/api/translations/[projectName]/[languageName]/[messageId]/route.ts, webapp/src/app/api/translations/[projectName]/[languageName]/route.ts, webapp/src/app/projects/[projectName]/[languageName]/page.tsx
Our route param names are currently a bit of a mish-mash of long-form compound names like `projectName` and highly abbreviated shorthands like `lang`. Here's how it'd look if either style were consistently applied across all routes.
| Long-form compound names | Highly abbreviated shorthand |
|-|-|
| `projectName` | `proj` |
| `languageName` | `lang` |
| `messageId` | `msgId` |
I think it's always easiest to establish a consistent pattern in this kind of stuff in the early days before the surface area grows to a point where it's an expensive thing to tidy up. Based on the above table my guess is that the long-form names are the ones we'd rather align on so this PR switches everything over to them.
In some cases this causes JSON response properties to change names in API responses. I think …
=> Align route param naming convention

.eslintrc.js, package.json, webapp/package.json, yarn.lock
eslint-config-next is built from the same source repository as next, and they are released together.
When we set up the boilerplate, the intializer set up the dependencies to use the same version. The versions only got out of sync later when we copied eslint configuration from app.zetking.org in e27f9cc5464ccc0a7c8a7eabe2c29d1869515f83
It is probably safer to keep next and eslint-config-next in sync.
I think this will make it easier or safer to update to next 14 later.
=> Update eslint-config-next to 13.5.6

package.json, yarn.lock
Next has its own integration with ESlint since Next 10.1 and it does not document any need to add eslint-loader.
https://github.com/vercel/next.js/pull/22437/
In that PR they implement their own next-eslint-loader: https://github.com/azukaru/next.js/blob/eeedc6935bcaedb85a9e386b3efd8321640f0682/packages/next/build/webpack/loaders/next-eslint-loader.ts
It is very similar to eslint-loader: https://github.com/webpack-contrib/eslint-loader/blob/master/src/index.js
Since Next 11, create-next-app sets up ESlint for you and it does not add eslint-loader.
By misordering properties in webapp/src/app/page.tsx, I have verified that lint:eslint still finds violation of rules.
=> Remove eslint-loader

.githooks/pre-commit
Almost every time I push I end up with a red build and have to push again cos I missed a lint error. I'm used to the [`.githooks/pre-commit`](https://github.com/zetkin/app.zetkin.org/blob/main/.githooks/pre-commit) config that the other repo has. Could we just have that here?
=> Add pre-commit hook

.eslintrc.js
In e27f9cc5464ccc0a7c8a7eabe2c29d1869515f83 we copied ESLint configuration from app.zetkin.org which specifically activates linting for .prettierrc.js
In Lyra, we use .prettierrc.json instead but json files are not linted by default, or by any extension we use.
See https://eslint.org/docs/v8.x/use/configure/configuration-files#specifying-target-files-to-lint
=> ESLint .prettierrc.json

webapp/README.md, webapp/src/app/api/projects/route.ts, webapp/src/app/projects/page.tsx, webapp/src/types.ts
Now that we have the pretty home page, there is no need for the old projects page except maybe as a base for a future administrator UI. An admin UI is pretty far away though and in the meantime, it is useful to reduce complexity as we expect some large changes in #25
=> Remove projects page

webapp/src/utils/git/SimpleGitWrapper.ts
Symbolic links could possible be used to escape the configured local repository path.
See #34
=> Disable git symlinks

webapp/src/utils/git/SimpleGitWrapper.ts, webapp/src/utils/lyraConfig.spec.ts, webapp/src/utils/lyraConfig.ts
By allowing strange language identifiers, and providing matching strange filenames, one who controls the repository could perhaps wreck some havoc in Lyra. Validation of language codes closes one avenue of such unintended manipulation.
This relates to #34 but is arguably not part of it.
=> Validate languages from lyra.yml

webapp/README.md
There's a couple of security warnings in the readme. Between them there's a paragraph of text that I don't think is intended to be a warning at all. Using GitHub's built-in `> [!WARNING` markdown syntax clarifies the semantics here quite a lot.
| Before | After |
|-|-|
| ![Screenshot 2024-07-06 at 10 16 20](https://github.com/zetkin/lyra/assets/566159/fbb2be13-8ee2-4865-8b54-eaeec19b5335) | ![Screenshot 2024-07-06 at 10 16 29](https://github.com/zetkin/lyra/assets/566159/68558999-b823-418e-94a8-c57f11428513) |
=> Use GitHub's !WARNING syntax for markdown warnings

webapp/src/app/projects/[projectName]/[languageName]/page.tsx, webapp/src/components/Breadcrumbs.tsx, webapp/src/components/Header.tsx, webapp/src/components/Main.tsx, webapp/src/components/Sidebar.tsx, webapp/src/theme.ts, webapp/src/theme.tsx
https://github.com/zetkin/lyra/issues/80
The Header component becomes always visible in this PR, so there's a bit of incidental paperwork included, which is associated with that change.
=> Add breadcrumb navigation

package-lock.json, webapp/package.json, webapp/src/components/MessageForm.tsx, webapp/src/components/MessageList.tsx, webapp/src/theme.ts
#82
Switches from a linear columnar layout to a side-by-side grid layout at the `lg` breakpoint.
On narrower devices, the MessageForm component's layout is linearised in order to fit everything in despite the lack of horizontal space. An increase in height is necessary for this. Its parent component, MessageList, needs to be able to configure a fixed height value to enable the virtualisation. So MessageForm exports a `messageFormHeight` function for this purpose.
As we have a little group of buttons underneath the text area, MUI's [ButtonGroup](https://mui.com/material-ui/react-button-group/) component seemed like a natural fit. And since we have a save button with a loading status, it seemed equally natural to pull in [LoadingButton](https://mui.com/material-ui/react-button/#loading-butto …
=> Implement Message Card design

webapp/src/app/projects/[projectName]/[languageName]/page.tsx, webapp/src/components/MessageTree.tsx, webapp/src/components/PullRequestButton.tsx, webapp/src/components/Sidebar.tsx, webapp/src/components/TitleBar.tsx
https://github.com/zetkin/lyra/issues/79
We don't have a means of differentiating the presence/absence of unpublished changes so I've ignored that detail intentionally.
| Before | After |
|-|-|
| ![Simulator Screenshot - iPhone 15 - 2024-07-14 at 20 39 21](https://github.com/user-attachments/assets/5f6ecd8d-ad9a-49e6-936d-f75c5c51054e) | ![Simulator Screenshot - iPhone 15 - 2024-07-14 at 20 37 07](https://github.com/user-attachments/assets/20da6e6a-1fd5-4ab4-8e81-d27993d350c5) |
| Before | After |
|-|-|
| ![Screenshot 2024-07-14 at 20 38 21](https://github.com/user-attachments/assets/4051f0f2-ed49-4614-91a3-b58d8748de41) | ![Screenshot 2024-07-14 at 20 38 12](https://github.com/user-attachments/assets/567d10e9-c0c7-498a-b1fc-d65a89a058a1) |
=> Change pull request button to publishing button

webapp/src/app/page.tsx, webapp/src/app/projects/[projectName]/page.tsx, webapp/src/dataAccess.ts, webapp/src/utils/Promises.ts
I think I want the data access layer just for the overview of the interactions with server state.
This change set contains some first steps towards a data access layer. I would like it reviewed before I continue as there are multiple small but non-trivial decisions made.
I recommend review commit-by-commit and consulting the commit messages for more detail.
=> Extract data access layer

webapp/.gitignore, webapp/src/actions/createPullRequest.ts
This adds a UUID snippet instead of a date string to the generated branch name used in the PR automation. 
Theoretically multiple branches with the same name could be created when using a string of Date.now() formatted as YYYY-mm-dd-hh:mm:ss as postfix to the branch submitted with the PR.
resolves #57
=> Add uuid snippet to branch name

webapp/src/app/projects/[projectName]/[languageName]/page.tsx, webapp/src/dataAccess.ts
This PR moves the data loading required for `MessagesPage` to the `dataAccess` module as a first step towards implementing cache revaliation. See issue #25 for game plan and motivations.
This is joint work by me and @WULCAN. We realized that further extraction and refactoring is possible, but chose not to do it now as it is not crucial for the cache issue, and can be done at a later point.
=> Extract MessagesPage data loading to dataAccess module

webapp/src/components/HomeDashboard.tsx
This PR adds padding to the home page so that content no longer touches the window edge when the window is small.
Try it out with larger and smaller windows.
This related to #71 but does not resolve it.
=> Pad Home page

webapp/src/store/ProjectStore.spec.ts, webapp/src/store/ProjectStore.ts
This PR fixes a bug where new translations got a source file prefixed with /, like an asbolute path, when the english translation's sourcefile was in the root of the translation path.
Source files prefixed with slash breaks the code that writes translations to disk when we create pull requests.
This relates to #126
=> Generate source file without leading slash

.eslintrc.js, .github/pull_request_template.md
This PR relaxes our ESLint configurtion to warn instead of fail the build on unused variables.
In #152 this rule blocks merging even though the added value from the pull request by far outweighs the introduced inconvenience. The reviewer can decide for herself instead wether unused variables needs to be fixed before or after merging.
See https://eslint.org/docs/v8.x/use/configure/rules for documentation.
* Changes the rule to severity `warn`
* Adds review of Test & Lint action output.
Resolves pull request #152
=> Relax ESLint

webapp/src/actions/updateTranslation.ts
fix error thrown on saving translation
prior to the fix, on click on save, it only kept 'thinking' forever
replace 'throw' with a return error message object
thank you for all your help
tested the issue by changing the if statement to if (true) in order to see the error no matter what
Resolves #146
=> fix error throwing in save message

webapp/README.md, webapp/src/RepoGit.ts, webapp/src/actions/createPullRequest.ts, webapp/src/dataAccess.ts, webapp/src/utils/git/IGit.ts, webapp/src/utils/git/SimpleGitWrapper.ts, webapp/src/utils/serverConfig.spec.ts, webapp/src/utils/serverConfig.ts
Solve the issue if main brach in local have diff history than remote one.
- instead of (checkout main then pull) now we (fetch then checkout origin/main) 
Resolves #147
=> Use fetch and checkout origin/main instead of pull

webapp/src/app/api/projects/[projectName]/languages/[languageId]/messages/[messageId]/route.ts, webapp/src/app/api/projects/[projectName]/pull-requests/route.ts, webapp/src/components/MessageForm.tsx, webapp/src/components/PullRequestButton.tsx
It was fun to try Next's server actions functionality here. I'm glad we merged that and had the opportunity to get some experience with it. But I think @amerharb has made some really good points about how limiting these server actions can become later. It does feel like a lot of vendor lock in.
I also think it could be handy to be able to automate requests to these endpoints. It's not certain that that's something we'll definitely want to do as part of writing automated Playwright tests. But I think it's nice to have the option on the table.
Here's a pull request that converts our server actions back into REST endpoints. I've tried to make this as small a code change as possible and I've manually verified that saving string changes and sending pull requests still works.
=> Reinstate REST API

.github/workflows/test-lint.yaml, package-lock.json, package.json, webapp/src/RepoGit.ts, webapp/src/store/Store.ts
@WULCAN find this interesting case in node where fs/promises writeFile that can effected us that we might write files but git commit and push the older version of these files related to a new flush option in writeFile: https://github.com/nodejs/node/pull/50009
write files with flush option true as `fs(path, body, { flush: true });` 
This change required upgrade to at least Node 21 so I updated to Node 22
=> Undocumented  use flush option in fs.writeFile()

.vscode/extensions.json, .vscode/settings.json, webapp/README.md
This PR configures Prettier as the default formatter in VS Code, so that developers do not have to configure it.
It also adds the extenension as a Recommended Extension to make it easier to install.
=> Automatically configure Prettier for VS Code

webapp/src/RepoGit.ts
Replace sync fs call `existsSync()` with async fs/promises call 
this the last use of 'fs' so all import now comes from 'fs/promises'
=> issue-61/Replace sync fs call existsSync with async fs/promises call 

.github/workflows/build-and-push-image.yaml
This PR removes docker/setup-docker-action
We are using GitHub-hosted runners on Linux so Docker is already up and running. It is not necessary to use docker/setup-docker-action
https://github.com/docker/setup-docker-action/blob/efe6ba76e30de04f1a84d4aa6ea0d802d73b31b9/README.md?plain=1#L12-L17.
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#tools
This is an amendment to pul request #157
=> Remove docker/setup-docker-action

webapp/CHANGELOG.md, webapp/src/utils/fileExists.spec.ts, webapp/src/utils/log.spec.ts, webapp/src/utils/log.ts
Disables Debug logging by default. It adds the possibility to turn it on with an env var
[Add screenshots here]
* Disables Debug logging by default
* Implements a possibility to turn it on via env var
* Adds a unit test for fileExists
You can test it with the unit test
Resolves #199
=> Issue 199/configurable loggin

package-lock.json, webapp/package.json
This PR removes @emotion from our direct dependencies.
As far as I can tell, we do not use it directly. npm will install it anyway as it is a peer dependency of our other dependencies.
Not declaring it in our package.json should give npm a little bit more freedom in choosing compatible versions.
I tested this with npm run dev and the UI still looks good.
Review the output of our GitHub action 'Test & Lint' for warnings.
Test that the UI is still styled appropriately.
This is a small step towards resolving #149
=> Remove @emotion from direct dependencies

package-lock.json, package.json, webapp/next.config.js, webapp/package.json
This PR updates Next to 14.2.30 and enabled the fix for CVE-2025-48068
Tested with npm run dev in webapp and live edits in source.
See commit messages for details.
Review the output of our GitHub action 'Test & Lint' for warnings.
=> next-14.2.30

package-lock.json, package.json
This PR remove eslint-plugin-next
In e27f9cc5464ccc0a7c8a7eabe2c29d1869515f83 we copied a dependency on eslint-plugin-next 0.0.0 from https://github.com/zetkin/app.zetkin.org/pull/559
The package is empty and does not originate from Next.js or Vercel.
In https://github.com/zetkin/app.zetkin.org/pull/2795, app.zetkin.org removed their dependency on the package.
I used npm uninstall eslint-plugin-next from npm 10.9.2
Review the output of our GitHub action 'Test & Lint' for warnings.
Resolves #197
=> Remove eslint-plugin-next
